module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 1
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 2
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 3
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 4
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 5
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 6
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 7
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 8
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 9
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 10
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 11
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 12
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 13
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 14
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 15
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 16
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 17
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 18
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 19
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 20
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 21
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 22
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 23
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 24
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 25
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 26
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 27
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 28
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 29
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 30
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 31
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 32
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 33
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 34
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 35
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 36
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 37
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 38
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 39
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 40
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 41
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 42
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 43
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 44
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 45
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 46
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 47
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 48
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 49
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 50
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 51
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 52
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 53
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 54
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 55
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 56
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 57
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 58
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 59
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 60
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 61
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 62
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 63
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 64
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 65
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 66
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 67
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 68
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 69
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 70
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 71
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 72
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 73
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 74
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 75
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 76
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 77
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 78
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 79
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 80
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 81
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 82
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 83
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 84
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 85
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 86
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 87
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 88
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 89
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 90
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 91
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 92
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 93
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 94
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 95
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 96
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 97
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 98
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 99
module load goal.stack && source mypy/bin/activate && python stocasticgreedy_randomwalk.py 100:
